<a href="https://colab.research.google.com/github/dhanagaraja/torch_tutorial/blob/main/basic_list.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch

In [2]:
my_nested_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_nested_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [3]:
np_array = np.array(my_nested_list)
np_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [11]:
np_random_array = np.random.rand(3,4)
print(np_random_array)
np_random_array.dtype

[[0.99880241 0.00846547 0.29642021 0.05047982]
 [0.43731691 0.81887417 0.66509561 0.36668676]
 [0.78295654 0.62662471 0.95271753 0.12758712]]


dtype('float64')

In [12]:
torch_random_array = torch.rand(3,4)
print(torch_random_array)
torch_random_array.dtype

tensor([[0.1007, 0.2660, 0.1100, 0.4705],
        [0.5887, 0.1599, 0.2650, 0.4614],
        [0.8839, 0.3505, 0.8124, 0.9384]])


torch.float32

**These are the examples of 2d arrays in numpy and torch**

In [16]:
torch_np_array = torch.from_numpy(np_array)
print(torch_np_array)
print(torch_np_array.dtype)
torch_np_random_array = torch.tensor(np_random_array)
print(torch_np_random_array)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])
torch.int64
tensor([[0.9988, 0.0085, 0.2964, 0.0505],
        [0.4373, 0.8189, 0.6651, 0.3667],
        [0.7830, 0.6266, 0.9527, 0.1276]], dtype=torch.float64)


**These are the examples of 3d arrays in numpy and torch**

In [17]:
torch_3d = torch.zeros(2,3,4)
torch_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [18]:
torch_3d = torch.rand(2,3,4)
torch_3d

tensor([[[0.9497, 0.5741, 0.2756, 0.5738],
         [0.6501, 0.1843, 0.1218, 0.9409],
         [0.5734, 0.3634, 0.1841, 0.6200]],

        [[0.6922, 0.5644, 0.2872, 0.9997],
         [0.6354, 0.6258, 0.1289, 0.9684],
         [0.6166, 0.4245, 0.1210, 0.6058]]])